### ISSUE TITLE
Dependency to towel-tags

### ISSUE THREAD

**Issue by mschmid** [matthiask/django-email-registration#10]
There seems to be a dependency to towel-tags, which is not documented, see template email_registration_form.html.
Could this be removed or made optional for simplicitys sake?

**Comment by matthiask** [comment]
Yes, this could be removed. Do you want to submit a pull request?

**Comment by mschmid** [comment]
Probably outdated

**Comment by matthiask** [comment]
I think this is still the case, but never mind. We'll address it if it comes up again.
