### ISSUE TITLE
template processors

### ISSUE THREAD

**Issue by marianobrc** [matthiask/django-email-registration#9]
Hello, i'm trying to integrate the app with my project and i'm getting the following arror while trying to render the registration form from the documentation:

TemplateSyntaxError at /register/new/

Invalid block tag: 'trans'

Request Method: 	GET
Request URL: 	http://localhost:8000/register/new/
Django Version: 	1.8.3
Exception Type: 	TemplateSyntaxError
Exception Value: 	

Invalid block tag: 'trans'

Exception Location: 	/home/diremar/registration-venv/lib/python3.4/site-packages/django/template/base.py in invalid_block_tag, line 395
Python Executable: 	/home/diremar/registration-venv/bin/python
Python Version: 	3.4.0
Python Path: 	

['/home/diremar/PycharmProjects/registration-test/register_test',
 '/home/diremar/PycharmProjects/registration-test/register_test',
 '/home/diremar/PycharmProjects/registration-test/register_test/register_test',
 '/home/diremar/PycharmProjects/registration-test/register_test/register_app',
 '/home/diremar/PycharmProjects/registration-test',
 '/home/diremar/registration-venv/lib/python3.4',
 '/home/diremar/registration-venv/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/diremar/registration-venv/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/diremar/registration-venv/lib/python3.4/site-packages']

Server time: 	Sat, 8 Aug 2015 02:40:17 +0000

I think i'm missing to include some tempate context processor to support the tag "trans", but i can't find that step on the doc.

Thanks, regards

**Comment by matthiask** [comment]
`trans` is a tag from Django's own i18n support. Maybe you are missing a `{% load i18n %}` statement somewhere in your templates?
